### ISSUE TITLE
filter: FilterParser very limited, failing spaces in attribute values

### ISSUE THREAD

**Issue by rawtaz** [audriga/scim-server-php#1]
While testing Azure AD SCIM provisioning with the PR for a Nextcloud app at https://lab.libreho.st/libre.sh/scim/scimserviceprovider/-/merge_requests/2 I discovered what I think is a limitation/bug in this SCIM library rather than the NC app.

In short, I got this error in the logs:
~~~
Opf\Models\SCIM\Standard\Filters\FilterException: Incorrectly formatted AttributeExpression in /var/www/html/custom_apps/scimserviceprovider/vendor/audriga/scim-server-php/src/Util/Filters/FilterParser.php:29
~~~

The request was:
~~~
GET /Groups?excludedAttributes=members&filter=displayName+eq+%22EDU+All+personal%22
~~~

So, the filter that is requested is this:
~~~
displayName eq "EDU All personal"
~~~

Looking at [`FilterParser::parseFilterExpression()`](https://github.com/audriga/scim-server-php/blob/main/src/Util/Filters/FilterParser.php#L19) it seems that it simply splits the filter string on the space character and verifies that the number of elements from that is two or three. It does not seem to take into account quoted values (strings are always quoted in this context), parentheses and similar filter formats.

As far as I can tell, spaces are perfectly valid in strings, according to the [SCIM Core specification](https://www.rfc-editor.org/rfc/rfc7643#page-9) which references the [JSON specification](https://www.rfc-editor.org/rfc/rfc7159#section-7). Regarding filter formats there is support for grouping using `()` and more complex filtering using `[]` described [here](https://www.rfc-editor.org/rfc/rfc7644#section-3.4.2.2).

On a related note, I noticed that while there's about six groups in the Azure AD I'm testing with, only two of them are synced. It seems that the two that are synced have no spaces in their names, while those that are not synced do have spaces in their names. So perhaps that part is related to spaces as well (could be due to a query failing due to the above filter issue, I haven't digged into this at all yet).

**Comment by JulienSchneider** [comment]
Hi!
Thanks for your feedback. Our filter support is quite limited for now but as this seems to break AzureAD sync we should definitely fix it. We will try to have a look asap ;)
The folder-with-space creation issue you are noticing may indeed be linked.

**Comment by rawtaz** [comment]
I found a couple of other libraries/works on the topic of SCIM filtering:

- https://github.com/tmilos/scim-filter-parser
- https://github.com/Cloudstek/scim-filter-parser (perhaps the most mature of them all, but the current version requires PHP 8.1 which might be a problem with NC)

**Comment by JulienSchneider** [comment]
Hi!
I just published a new version of scim-server-php. While this version still implement filters in a very limited way, the spaces issue should be fixed. It also fixes a bug in groups membership.

**Comment by rawtaz** [comment]
Nice, great job! Should probably have been put into two separate commits as the changes are totally unrelated, but whatever. I also noticed that you added a test for spaces in user but not in group. I'll see if I can try this change soon.
